services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  express-server:
    build:
      context: ./my-express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./my-express-server/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      